// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaApi.Data;

#nullable disable

namespace SubastaApi.Migrations
{
    [DbContext(typeof(SubastaDbContext))]
    [Migration("20260606061800_AddDecimalPrecision")]
    partial class AddDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubastaApi.Entidades.Calificacion", b =>
                {
                    b.Property<int>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalificacion"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CveSubasta")
                        .HasColumnType("int");

                    b.Property<int>("CveUsuarioCalificado")
                        .HasColumnType("int");

                    b.Property<int>("CveUsuarioCalificador")
                        .HasColumnType("int");

                    b.Property<int>("Estrellas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCalificacion");

                    b.HasIndex("CveSubasta")
                        .IsUnique();

                    b.HasIndex("CveUsuarioCalificado");

                    b.HasIndex("CveUsuarioCalificador");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Vehículo"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Inmueble"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Electronicos"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Descripcion = "Arte y coleccionables"
                        },
                        new
                        {
                            IdCategoria = 5,
                            Descripcion = "Antiguedades"
                        },
                        new
                        {
                            IdCategoria = 6,
                            Descripcion = "Ropas y accesorios"
                        },
                        new
                        {
                            IdCategoria = 7,
                            Descripcion = "Articulos deportivos"
                        },
                        new
                        {
                            IdCategoria = 8,
                            Descripcion = "Libros"
                        },
                        new
                        {
                            IdCategoria = 9,
                            Descripcion = "Juguetes"
                        },
                        new
                        {
                            IdCategoria = 10,
                            Descripcion = "Contenidos digitales"
                        },
                        new
                        {
                            IdCategoria = 11,
                            Descripcion = "Entrada a eventos"
                        });
                });

            modelBuilder.Entity("SubastaApi.Entidades.Condicion", b =>
                {
                    b.Property<int>("IdCondicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCondicion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCondicion");

                    b.ToTable("Condiciones");

                    b.HasData(
                        new
                        {
                            IdCondicion = 1,
                            Descripcion = "Nuevo"
                        },
                        new
                        {
                            IdCondicion = 2,
                            Descripcion = "Usado"
                        },
                        new
                        {
                            IdCondicion = 3,
                            Descripcion = "Reacondicionado"
                        });
                });

            modelBuilder.Entity("SubastaApi.Entidades.FotoProducto", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("CveProducto")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFoto");

                    b.HasIndex("CveProducto");

                    b.ToTable("FotosProducto");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Inmueble", b =>
                {
                    b.Property<int>("IdInmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInmueble"));

                    b.Property<int>("CveProducto")
                        .HasColumnType("int");

                    b.Property<int>("NumeroHabitaciones")
                        .HasColumnType("int");

                    b.Property<int>("SuperficieConstruida")
                        .HasColumnType("int");

                    b.Property<int>("SuperficieTerreno")
                        .HasColumnType("int");

                    b.Property<string>("UrlDocumentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInmueble");

                    b.HasIndex("CveProducto")
                        .IsUnique();

                    b.ToTable("Inmuebles");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<int?>("CveOferta")
                        .HasColumnType("int");

                    b.Property<int?>("CveSubasta")
                        .HasColumnType("int");

                    b.Property<int>("CveTipoNotificacion")
                        .HasColumnType("int");

                    b.Property<int>("CveUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("CveOferta");

                    b.HasIndex("CveSubasta");

                    b.HasIndex("CveTipoNotificacion");

                    b.HasIndex("CveUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Oferta", b =>
                {
                    b.Property<int>("IdOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOferta"));

                    b.Property<int>("CveSubasta")
                        .HasColumnType("int");

                    b.Property<int>("CveUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOferta");

                    b.HasIndex("CveSubasta");

                    b.HasIndex("CveUsuario");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int>("CveStatusPago")
                        .HasColumnType("int");

                    b.Property<int>("CveSubasta")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPago");

                    b.HasIndex("CveStatusPago");

                    b.HasIndex("CveSubasta")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<int>("CveCategoria")
                        .HasColumnType("int");

                    b.Property<int>("CveCondicion")
                        .HasColumnType("int");

                    b.Property<int>("CveStatusProducto")
                        .HasColumnType("int");

                    b.Property<int>("CveUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducto");

                    b.HasIndex("CveCategoria");

                    b.HasIndex("CveCondicion");

                    b.HasIndex("CveStatusProducto");

                    b.HasIndex("CveUsuario");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SubastaApi.Entidades.StatusPago", b =>
                {
                    b.Property<int>("IdStatusPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusPago"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatusPago");

                    b.ToTable("StatusPagos");

                    b.HasData(
                        new
                        {
                            IdStatusPago = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            IdStatusPago = 2,
                            Descripcion = "Pagado"
                        },
                        new
                        {
                            IdStatusPago = 3,
                            Descripcion = "Vencido"
                        });
                });

            modelBuilder.Entity("SubastaApi.Entidades.StatusProducto", b =>
                {
                    b.Property<int>("IdStatusProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatusProducto");

                    b.ToTable("StatusProductos");

                    b.HasData(
                        new
                        {
                            IdStatusProducto = 1,
                            Descripcion = "Disponible"
                        },
                        new
                        {
                            IdStatusProducto = 2,
                            Descripcion = "En Subasta"
                        },
                        new
                        {
                            IdStatusProducto = 3,
                            Descripcion = "Vendido"
                        },
                        new
                        {
                            IdStatusProducto = 4,
                            Descripcion = "Retirado"
                        });
                });

            modelBuilder.Entity("SubastaApi.Entidades.StatusSubasta", b =>
                {
                    b.Property<int>("IdStatusSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusSubasta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatusSubasta");

                    b.ToTable("StatusSubastas");

                    b.HasData(
                        new
                        {
                            IdStatusSubasta = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            IdStatusSubasta = 2,
                            Descripcion = "Activa"
                        },
                        new
                        {
                            IdStatusSubasta = 3,
                            Descripcion = "Finalizada"
                        },
                        new
                        {
                            IdStatusSubasta = 4,
                            Descripcion = "Cancelada"
                        });
                });

            modelBuilder.Entity("SubastaApi.Entidades.Subasta", b =>
                {
                    b.Property<int>("IdSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubasta"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CveProducto")
                        .HasColumnType("int");

                    b.Property<int>("CveStatusSubasta")
                        .HasColumnType("int");

                    b.Property<int>("CveTipoSubasta")
                        .HasColumnType("int");

                    b.Property<int?>("CveUsuarioGanador")
                        .HasColumnType("int");

                    b.Property<decimal>("Decremento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Incremento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSubasta");

                    b.HasIndex("CveProducto");

                    b.HasIndex("CveStatusSubasta");

                    b.HasIndex("CveTipoSubasta");

                    b.HasIndex("CveUsuarioGanador");

                    b.ToTable("Subastas");
                });

            modelBuilder.Entity("SubastaApi.Entidades.TipoNotificacion", b =>
                {
                    b.Property<int>("IdTipoNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoNotificacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoNotificacion");

                    b.ToTable("TiposNotificacion");

                    b.HasData(
                        new
                        {
                            IdTipoNotificacion = 1,
                            Descripcion = "Oferta Recibida"
                        },
                        new
                        {
                            IdTipoNotificacion = 2,
                            Descripcion = "Oferta Superada"
                        },
                        new
                        {
                            IdTipoNotificacion = 3,
                            Descripcion = "Pago Pendiente"
                        });
                });

            modelBuilder.Entity("SubastaApi.Entidades.TipoSubasta", b =>
                {
                    b.Property<int>("IdTipoSubasta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoSubasta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoSubasta");

                    b.ToTable("TiposSubasta");

                    b.HasData(
                        new
                        {
                            IdTipoSubasta = 1,
                            Descripcion = "Inglesa"
                        },
                        new
                        {
                            IdTipoSubasta = 2,
                            Descripcion = "Holandesa"
                        },
                        new
                        {
                            IdTipoSubasta = 3,
                            Descripcion = "Sellada"
                        });
                });

            modelBuilder.Entity("SubastaApi.Entidades.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TiposUsuario");

                    b.HasData(
                        new
                        {
                            IdTipoUsuario = 1,
                            Descripcion = "Administrador"
                        },
                        new
                        {
                            IdTipoUsuario = 2,
                            Descripcion = "Vendedor"
                        },
                        new
                        {
                            IdTipoUsuario = 3,
                            Descripcion = "Comprador"
                        });
                });

            modelBuilder.Entity("SubastaApi.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CveTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("CveTipoUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("CveProducto")
                        .HasColumnType("int");

                    b.Property<float>("Kilometraje")
                        .HasColumnType("real");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("int");

                    b.Property<string>("UrlDocumentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("CveProducto")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Calificacion", b =>
                {
                    b.HasOne("SubastaApi.Entidades.Subasta", "SubastaRef")
                        .WithOne("CalificacionRef")
                        .HasForeignKey("SubastaApi.Entidades.Calificacion", "CveSubasta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.Usuario", "UsuarioCalificado")
                        .WithMany("CalificacionesRecibidas")
                        .HasForeignKey("CveUsuarioCalificado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.Usuario", "UsuarioCalificador")
                        .WithMany("CalificacionesDadas")
                        .HasForeignKey("CveUsuarioCalificador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubastaRef");

                    b.Navigation("UsuarioCalificado");

                    b.Navigation("UsuarioCalificador");
                });

            modelBuilder.Entity("SubastaApi.Entidades.FotoProducto", b =>
                {
                    b.HasOne("SubastaApi.Entidades.Producto", "ProductoRef")
                        .WithMany("Fotos")
                        .HasForeignKey("CveProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Inmueble", b =>
                {
                    b.HasOne("SubastaApi.Entidades.Producto", "ProductoRef")
                        .WithOne("InmuebleRef")
                        .HasForeignKey("SubastaApi.Entidades.Inmueble", "CveProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Notificacion", b =>
                {
                    b.HasOne("SubastaApi.Entidades.Oferta", "OfertaRef")
                        .WithMany("Notificaciones")
                        .HasForeignKey("CveOferta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubastaApi.Entidades.Subasta", "SubastaRef")
                        .WithMany("Notificaciones")
                        .HasForeignKey("CveSubasta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubastaApi.Entidades.TipoNotificacion", "TipoNotificacionRef")
                        .WithMany("Notificaciones")
                        .HasForeignKey("CveTipoNotificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.Usuario", "UsuarioRef")
                        .WithMany("Notificaciones")
                        .HasForeignKey("CveUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfertaRef");

                    b.Navigation("SubastaRef");

                    b.Navigation("TipoNotificacionRef");

                    b.Navigation("UsuarioRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Oferta", b =>
                {
                    b.HasOne("SubastaApi.Entidades.Subasta", "SubastaRef")
                        .WithMany("Ofertas")
                        .HasForeignKey("CveSubasta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.Usuario", "UsuarioRef")
                        .WithMany("Ofertas")
                        .HasForeignKey("CveUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubastaRef");

                    b.Navigation("UsuarioRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Pago", b =>
                {
                    b.HasOne("SubastaApi.Entidades.StatusPago", "StatusPagoRef")
                        .WithMany("Pagos")
                        .HasForeignKey("CveStatusPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.Subasta", "SubastaRef")
                        .WithOne("PagoRef")
                        .HasForeignKey("SubastaApi.Entidades.Pago", "CveSubasta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StatusPagoRef");

                    b.Navigation("SubastaRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Producto", b =>
                {
                    b.HasOne("SubastaApi.Entidades.Categoria", "CategoriaRef")
                        .WithMany("Productos")
                        .HasForeignKey("CveCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.Condicion", "CondicionRef")
                        .WithMany("Productos")
                        .HasForeignKey("CveCondicion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.StatusProducto", "StatusProductoRef")
                        .WithMany("Productos")
                        .HasForeignKey("CveStatusProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.Usuario", "UsuarioRef")
                        .WithMany("Productos")
                        .HasForeignKey("CveUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaRef");

                    b.Navigation("CondicionRef");

                    b.Navigation("StatusProductoRef");

                    b.Navigation("UsuarioRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Subasta", b =>
                {
                    b.HasOne("SubastaApi.Entidades.Producto", "ProductoRef")
                        .WithMany("Subastas")
                        .HasForeignKey("CveProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.StatusSubasta", "StatusSubastaRef")
                        .WithMany("Subastas")
                        .HasForeignKey("CveStatusSubasta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.TipoSubasta", "TipoSubastaRef")
                        .WithMany("Subastas")
                        .HasForeignKey("CveTipoSubasta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaApi.Entidades.Usuario", "UsuarioGanadorRef")
                        .WithMany("Subastas")
                        .HasForeignKey("CveUsuarioGanador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductoRef");

                    b.Navigation("StatusSubastaRef");

                    b.Navigation("TipoSubastaRef");

                    b.Navigation("UsuarioGanadorRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Usuario", b =>
                {
                    b.HasOne("SubastaApi.Entidades.TipoUsuario", "TipoUsuarioRef")
                        .WithMany("Usuarios")
                        .HasForeignKey("CveTipoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoUsuarioRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Vehiculo", b =>
                {
                    b.HasOne("SubastaApi.Entidades.Producto", "ProductoRef")
                        .WithOne("VehiculoRef")
                        .HasForeignKey("SubastaApi.Entidades.Vehiculo", "CveProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Condicion", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Oferta", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Producto", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("InmuebleRef");

                    b.Navigation("Subastas");

                    b.Navigation("VehiculoRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.StatusPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SubastaApi.Entidades.StatusProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SubastaApi.Entidades.StatusSubasta", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Subasta", b =>
                {
                    b.Navigation("CalificacionRef");

                    b.Navigation("Notificaciones");

                    b.Navigation("Ofertas");

                    b.Navigation("PagoRef");
                });

            modelBuilder.Entity("SubastaApi.Entidades.TipoNotificacion", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("SubastaApi.Entidades.TipoSubasta", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("SubastaApi.Entidades.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SubastaApi.Entidades.Usuario", b =>
                {
                    b.Navigation("CalificacionesDadas");

                    b.Navigation("CalificacionesRecibidas");

                    b.Navigation("Notificaciones");

                    b.Navigation("Ofertas");

                    b.Navigation("Productos");

                    b.Navigation("Subastas");
                });
#pragma warning restore 612, 618
        }
    }
}
